# Site settings
title: Today I learned
description: >- # ignore newlines until next key
  Programming is my passion.
  I learn something new everyday.
baseurl: '/til'
url: &url https://torrocus.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

exclude:
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /:title/
feed:
  excerpt_only: true

languages: ['en', 'pl']
default_lang: en
exclude_from_localization: &exclude_from_localization ['_drafts', 'assets', 'README.md']
exclude_from_localizations: *exclude_from_localization
parallel_localization: true

sass:
  style: compressed
